### ISSUE TITLE
As a Super-User I want to assign users manually to notice boards

### ISSUE THREAD

**Issue by MistereoSC** [conclurer/midnightboard#111] opened 2019-11-27 15:04 UTC
Acceptance criteria:
- [ ] Each notice board should display a "assign" button similar to the "invite" button.
- [ ] Users invited this way, should automatically be added to the board.
- [ ] The "assign" button should only be visible to Super-Users.

**Comment by DevPhilB** [comment] 2019-12-04 09:38
Duplicate of #44

**Closed by DevPhilB** 2019-12-04 09:38 UTC
